language: node_js
node_js:
- 6.11.5
before_script:
- cd functions
- npm install -g firebase-tools
- npm install
cache:
  directories:
  - functions/node_modules
after_success:
- pwd
- firebase deploy --only functions -P production --token $FIREBASE_DEPLOY_TOKEN --debug